# Generated by Django 5.1.4 on 2025-02-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('contacts', '0002_alter_contact_code_alter_customer_alias_and_more'),
        ('finance', '0002_alter_financialtransaction_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Paid', 'paid'), ('Overdue', 'overdue'), ('Partially Paid', 'partially_paid')], max_length=150)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=255)),
                ('notes', models.TextField(max_length=500)),
                ('recurrence', models.CharField(choices=[('Once', 'once'), ('Weekly', 'weekly'), ('Monthly', 'monthly'), ('Annually', 'annually'), ('Installments', 'installments')], max_length=150)),
                ('installments', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Payable', 'payalbe'), ('Receivable', 'receivable')], max_length=150)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='business.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='finance.financialcategory')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contacts.contact')),
            ],
        ),
    ]
