# Generated by Django 5.1.4 on 2025-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recurrence',
            field=models.CharField(choices=[('Once', 'once'), ('Weekly', 'weekly'), ('Monthly', 'monthly'), ('Annually', 'annually'), ('Installments', 'installments')], default='once', max_length=150),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Payable', 'payable'), ('Receivable', 'receivable')], max_length=150),
        ),
    ]
