# Generated by Django 5.1.4 on 2025-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_payment_due_day_payment_due_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='installments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
