# Generated by Django 5.1.4 on 2025-02-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_payment_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='installments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
