# Generated by Django 5.1.4 on 2025-02-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_payment_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Once'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('installments', 'Installments')], default='once', max_length=150),
        ),
    ]
