# Generated by Django 5.1.4 on 2025-02-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_payment_recurrence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='due_date',
            new_name='due_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='due_day',
            new_name='due_day_of_month',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='installments',
            new_name='installment_count',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='issue_date',
            new_name='issue_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.AddField(
            model_name='payment',
            name='outstanding_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('payable', 'Payable'), ('receivable', 'Receivable')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
