# Generated by Django 5.1.4 on 2025-02-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_payment_outstanding_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='issue_at',
            new_name='issued_at',
        ),
    ]
