# Generated by Django 5.1.4 on 2025-02-12 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_payment_amount_paid_and_more'),
        ('finance', '0002_alter_financialtransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='finance.financialtransaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
