# Generated by Django 5.1.4 on 2025-02-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_payment_transaction_alter_payment_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
    ]
