# Generated by Django 5.1.4 on 2025-02-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_remove_payment_created_at'),
        ('finance', '0002_alter_financialtransaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ManyToManyField(blank=True, null=True, related_name='payments', to='finance.financialtransaction'),
        ),
    ]
