# Generated by Django 5.1.4 on 2025-02-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_remove_payment_transaction_payment_transaction'),
        ('finance', '0002_alter_financialtransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.ManyToManyField(related_name='payments', to='finance.financialtransaction'),
        ),
    ]
