# Generated by Django 5.1.4 on 2025-02-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_payment_transaction'),
        ('finance', '0002_alter_financialtransaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.financialtransaction'),
        ),
    ]
