# Generated by Django 5.1.4 on 2025-02-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_remove_payment_transaction_payment_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
    ]
