# Generated by Django 5.1.4 on 2024-12-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='modules_products.category')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('trackStock', models.BooleanField(default=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('ncm', models.CharField(blank=True, max_length=10)),
                ('barcode', models.IntegerField(blank=True, null=True)),
                ('cest', models.CharField(blank=True, max_length=20)),
                ('costPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retailPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discountedPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='modules_products.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='CostHistory',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('quatity', models.PositiveIntegerField(default=0)),
                ('effectiveDate', models.DateField()),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costAverage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retailPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='modules_products.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('source_object_id', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='modules_products.products')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sources', to='contenttypes.contenttype')),
            ],
        ),
    ]
