# Generated by Django 5.1.4 on 2025-01-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0005_alter_products_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
