# Generated by Django 5.1.4 on 2025-01-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0006_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, default='ACTIVE', max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(blank=True, default='ACTIVE', max_length=150),
        ),
    ]
