# Generated by Django 5.1.4 on 2025-01-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0008_remove_products_supplier_products_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costhistory',
            name='source',
        ),
    ]
