# Generated by Django 5.1.4 on 2025-01-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0009_remove_costhistory_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costhistory',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
