# Generated by Django 5.1.4 on 2025-01-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0010_rename_quatity_costhistory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costhistory',
            name='costAverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
