# Generated by Django 5.1.4 on 2025-01-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0011_alter_costhistory_costaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costhistory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
