# Generated by Django 5.1.4 on 2025-01-05 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_animals', '0003_alter_animalhealth_options_and_more'),
        ('modules_products', '0012_alter_costhistory_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagingDate', models.DateField(blank=True, null=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='modules_animals.animal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='modules_products.products')),
            ],
        ),
    ]
