# Generated by Django 5.1.4 on 2025-01-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_animals', '0003_alter_animalhealth_options_and_more'),
        ('modules_products', '0013_productanimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productanimal',
            options={'verbose_name_plural': 'Animal Product'},
        ),
        migrations.RemoveField(
            model_name='productanimal',
            name='animal',
        ),
        migrations.AddField(
            model_name='productanimal',
            name='animal',
            field=models.ManyToManyField(related_name='products', to='modules_animals.animal'),
        ),
    ]
