# Generated by Django 5.1.4 on 2025-01-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0014_alter_productanimal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productanimal',
            name='id',
            field=models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
