# Generated by Django 5.1.4 on 2024-12-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='taxPayer',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
