# Generated by Django 5.1.4 on 2025-01-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcosthistory',
            old_name='cost_average',
            new_name='average_cost',
        ),
    ]
