# Generated by Django 5.1.4 on 2024-12-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='costhistory',
            options={'verbose_name_plural': 'Cost History'},
        ),
        migrations.AlterModelOptions(
            name='productsource',
            options={'verbose_name_plural': 'Sources'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='modules_products.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
