# Generated by Django 5.1.4 on 2025-01-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_contacts', '0006_alter_contacts_entityid'),
        ('modules_products', '0002_alter_category_options_alter_costhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='modules_contacts.contacts'),
        ),
        migrations.DeleteModel(
            name='ProductSource',
        ),
    ]
