# Generated by Django 5.1.4 on 2025-01-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0003_products_supplier_delete_productsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
