# Generated by Django 5.1.4 on 2025-01-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_contacts', '0006_alter_contacts_entityid'),
        ('modules_products', '0007_category_status_alter_products_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='supplier',
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ManyToManyField(blank=True, related_name='products', to='modules_contacts.contacts'),
        ),
    ]
