# Generated by Django 5.1.4 on 2025-01-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_products', '0015_alter_productanimal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='costPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
