# Generated by Django 5.1.4 on 2025-01-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_owner_name_alter_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
