# Generated by Django 5.1.4 on 2025-01-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_owner_business'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='business.business'),
        ),
    ]
