# Generated by Django 5.1.4 on 2025-01-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='business',
        ),
    ]
