# Generated by Django 5.1.4 on 2025-01-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='linked_transaction',
            new_name='linked',
        ),
    ]
