# Generated by Django 5.1.4 on 2025-02-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_remove_payment_transaction'),
        ('finance', '0003_financialtransaction_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='billing.payment'),
        ),
    ]
