# Generated by Django 5.1.4 on 2025-01-16 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_street_address_business_address_and_more'),
        ('contacts', '0007_rename_name_supplier_legal_name'),
        ('finance', '0004_rename_transaction_financialtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='business',
            field=models.ForeignKey(default='01JHFW109W6Y4NCZB05D5BHQY8', on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='business.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='finance.financialaccount'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='financial_transactions', to='finance.financialcategory'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
