# Generated by Django 5.1.4 on 2025-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('legal_name', models.CharField(max_length=150)),
                ('trade_name', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=14, unique=True)),
                ('state_registration', models.CharField(blank=True, max_length=14)),
                ('city_registration', models.CharField(blank=True, max_length=14)),
                ('street_address', models.CharField(blank=True, max_length=150)),
                ('address_number', models.CharField(blank=True, max_length=10)),
                ('neighborhood', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postcode', models.CharField(blank=True, max_length=8)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
