# Generated by Django 5.1.4 on 2024-12-20 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(default='01JFHZYN0F2TGXGCZ6CPA0A4PD', max_length=26, primary_key=True, serialize=False)),
                ('legalName', models.CharField(max_length=150)),
                ('tradeName', models.CharField(max_length=150)),
                ('registrationNumber', models.CharField(max_length=14, unique=True)),
                ('stateRegistration', models.CharField(blank=True, max_length=14)),
                ('cityRegistration', models.CharField(blank=True, max_length=14)),
                ('companyType', models.CharField(blank=True, max_length=150)),
                ('streetAddress', models.CharField(blank=True, max_length=150)),
                ('addressNumber', models.CharField(blank=True, max_length=10)),
                ('neighborhood', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postCode', models.CharField(blank=True, max_length=8)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
