# Generated by Django 5.1.4 on 2024-12-20 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(default='01JFJ1B1XZSP18ZHZQTMP5QXNG', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='modules_business.business')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
