# Generated by Django 5.1.4 on 2025-01-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='additional_info',
            new_name='address_extra',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='address_number',
            new_name='building_number',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='registration_number',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='city_registration',
            new_name='ie',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='state_registration',
            new_name='im',
        ),
    ]
