# Generated by Django 5.1.4 on 2025-01-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_additional_info_business_address_extra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='street_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='business',
            name='address_extra',
        ),
        migrations.RemoveField(
            model_name='business',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='neighborhood',
        ),
    ]
