# Generated by Django 5.1.4 on 2024-12-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0004_alter_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(default='01JFJW37AGQDPDW0C6CCKDZ0J2', max_length=26, primary_key=True, serialize=False),
        ),
    ]
