# Generated by Django 5.1.4 on 2024-12-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0005_alter_business_email_alter_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
