# Generated by Django 5.1.4 on 2024-12-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0006_alter_business_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Business'},
        ),
        migrations.AlterModelOptions(
            name='businessowner',
            options={'verbose_name_plural': 'Business Owner'},
        ),
    ]
