# Generated by Django 5.1.4 on 2024-12-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0007_alter_business_options_alter_businessowner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='businessowner',
            options={'verbose_name_plural': 'Business Owners'},
        ),
    ]
