# Generated by Django 5.1.4 on 2024-12-23 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0008_alter_business_options_alter_businessowner_options'),
        ('modules_members', '0005_remove_members_personalid_members_taxid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='modules_business.business')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='modules_members.members')),
            ],
            options={
                'verbose_name_plural': 'Business Members',
            },
        ),
    ]
