# Generated by Django 5.1.4 on 2024-12-23 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0010_rename_members_businessmembers_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembers',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='modules_business.business'),
        ),
    ]
