# Generated by Django 5.1.4 on 2024-12-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0011_alter_businessmembers_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembers',
            name='id',
            field=models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='id',
            field=models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
