# Generated by Django 5.1.4 on 2024-12-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0012_alter_businessmembers_id_alter_businessowner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='additionalInfo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
