# Generated by Django 5.1.4 on 2024-12-26 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0013_business_additionalinfo'),
        ('modules_contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContacts',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_contacts', to='modules_business.business')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_contacts', to='modules_contacts.contacts')),
            ],
            options={
                'verbose_name_plural': 'Business Contacts',
            },
        ),
    ]
