# Generated by Django 5.1.4 on 2025-01-03 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0016_businessproductscategories'),
        ('modules_products', '0007_category_status_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproductscategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='modules_products.category'),
        ),
    ]
