# Generated by Django 5.1.4 on 2025-01-07 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0018_alter_businessproductscategories_options'),
        ('modules_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBankAccounts',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('bankAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='modules_finance.bankaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='modules_business.business')),
            ],
        ),
    ]
