# Generated by Django 5.1.4 on 2025-01-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0020_alter_businessbankaccounts_options'),
        ('modules_finance', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessFinanceCategories',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('bankAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='modules_finance.category')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_categories', to='modules_business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Finance Categories',
            },
        ),
    ]
