# Generated by Django 5.1.4 on 2025-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='id',
            field=models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
