# Generated by Django 5.1.4 on 2025-01-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'verbose_name_plural': 'Inventory Transactions'},
        ),
    ]
