# Generated by Django 5.1.4 on 2025-01-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_inventory', '0002_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transactionType',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('balance', 'Balance')], max_length=100),
        ),
    ]
