# Generated by Django 5.1.4 on 2025-01-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_inventory', '0003_alter_inventorytransaction_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='unitPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
