# Generated by Django 5.1.4 on 2025-01-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorytransaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='type',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=100),
        ),
    ]
