# Generated by Django 5.1.4 on 2024-12-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
                ('personalId', models.CharField(blank=True, max_length=11)),
                ('dateOfBirth', models.DateField()),
                ('role', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('access', models.BooleanField(default=False)),
                ('hireDate', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(max_length=150)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('streetAddress', models.CharField(blank=True, max_length=150)),
                ('addressNumber', models.CharField(blank=True, max_length=10)),
                ('neighborhood', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postCode', models.CharField(blank=True, max_length=8)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
    ]
