# Generated by Django 5.1.4 on 2024-12-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='hireDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='members',
            name='role',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
