# Generated by Django 5.1.4 on 2024-12-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_members', '0004_alter_members_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='personalId',
        ),
        migrations.AddField(
            model_name='members',
            name='taxId',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
