# Generated by Django 5.1.4 on 2024-12-23 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_members', '0006_alter_memberscredentials_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberscredentials',
            name='credentials',
        ),
        migrations.AddField(
            model_name='memberscredentials',
            name='credential',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberscredentials',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='modules_members.members'),
        ),
    ]
