# Generated by Django 5.1.4 on 2024-12-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JF6KSAG2SW1F2SG1HQ32CHY5', max_length=26, primary_key=True, serialize=False),
        ),
    ]
