# Generated by Django 5.1.4 on 2024-12-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JF890R8E7DXCK30ME4HTC93W', max_length=26, primary_key=True, serialize=False),
        ),
    ]
