# Generated by Django 5.1.4 on 2024-12-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JF8EA645FXVF2D3Z7RAVGYSZ', max_length=26, primary_key=True, serialize=False),
        ),
    ]
