# Generated by Django 5.1.4 on 2024-12-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JFBE3M6SRDZFES7A64T7XJXJ', max_length=26, primary_key=True, serialize=False),
        ),
    ]
