# Generated by Django 5.1.4 on 2024-12-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JFBJD21N1367AYW2M01Z2XYX', max_length=26, primary_key=True, serialize=False),
        ),
    ]
