# Generated by Django 5.1.4 on 2024-12-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JFBNQH95ZWFJHKN8X5Z2SVC0', max_length=26, primary_key=True, serialize=False),
        ),
    ]
