# Generated by Django 5.1.4 on 2024-12-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JFBP4F29JVWES38702FP8MPX', max_length=26, primary_key=True, serialize=False),
        ),
    ]
