# Generated by Django 5.1.4 on 2024-12-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JFJ1B1XXWGB8P98B54AFQNTC', max_length=26, primary_key=True, serialize=False),
        ),
    ]
