# Generated by Django 5.1.4 on 2024-12-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JFJP9BFX3E9GTTYRPC2K7SG1', max_length=26, primary_key=True, serialize=False),
        ),
    ]
