# Generated by Django 5.1.4 on 2024-12-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JFJSAN7BB5B0S747ZXBTK06G', max_length=26, primary_key=True, serialize=False),
        ),
    ]
