# Generated by Django 5.1.4 on 2024-12-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='01JFJW37AFRFN7H81ERNAWTSQ9', max_length=26, primary_key=True, serialize=False),
        ),
    ]
