# Generated by Django 5.1.4 on 2025-01-09 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules_contacts', '0006_alter_contacts_entityid'),
        ('modules_finance', '0002_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bankAccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='modules_finance.bankaccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='modules_finance.category')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='modules_contacts.contacts')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('linkedTransaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules_transactions.transaction')),
            ],
        ),
    ]
