# Generated by Django 5.1.4 on 2025-01-09 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_contacts', '0006_alter_contacts_entityid'),
        ('modules_transactions', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='modules_contacts.contacts'),
        ),
    ]
