# Generated by Django 5.1.4 on 2025-01-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0022_rename_bankaccount_businessfinancecategories_category'),
        ('modules_transactions', '0004_alter_transaction_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(default='01JG84B5C8ET4J2QVD2S2Q2276', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='modules_business.business'),
            preserve_default=False,
        ),
    ]
