# Generated by Django 5.1.4 on 2024-12-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0002_remove_business_owner_alter_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(default='01JFJP9BFYVHBM7CRD51VH7WS6', max_length=26, primary_key=True, serialize=False),
        ),
    ]
