# Generated by Django 5.1.4 on 2024-12-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0003_business_active_alter_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(default='01JFJSAN7C92JFKMGNKAKGKR93', max_length=26, primary_key=True, serialize=False),
        ),
    ]
