# Generated by Django 5.1.4 on 2024-12-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0009_businessmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessmembers',
            old_name='members',
            new_name='member',
        ),
    ]
