# Generated by Django 5.1.4 on 2024-12-30 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0014_businesscontacts'),
        ('modules_products', '0002_alter_category_options_alter_costhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProducts',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_products', to='modules_business.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_products', to='modules_products.products')),
            ],
            options={
                'verbose_name_plural': 'Business Products',
            },
        ),
    ]
