# Generated by Django 5.1.4 on 2025-01-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0015_businessproducts'),
        ('modules_products', '0007_category_status_alter_products_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProductsCategories',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='modules_business.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='modules_products.category')),
            ],
        ),
    ]
