# Generated by Django 5.1.4 on 2025-01-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0017_alter_businessproductscategories_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessproductscategories',
            options={'verbose_name_plural': 'Business Products Categories'},
        ),
    ]
