# Generated by Django 5.1.4 on 2025-01-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0019_businessbankaccounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessbankaccounts',
            options={'verbose_name_plural': 'Business Bank Accounts'},
        ),
    ]
