# Generated by Django 5.1.4 on 2025-01-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_business', '0021_businessfinancecategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessfinancecategories',
            old_name='bankAccount',
            new_name='category',
        ),
    ]
