# Generated by Django 5.1.4 on 2025-01-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_credentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='credentials',
            new_name='credential',
        ),
    ]
