# Generated by Django 5.1.4 on 2024-12-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_members', '0003_memberscredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
