# Generated by Django 5.1.4 on 2025-01-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_credentials_member_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
