# Generated by Django 5.1.4 on 2024-12-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_members', '0005_remove_members_personalid_members_taxid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscredentials',
            name='id',
            field=models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
