# Generated by Django 5.1.4 on 2024-12-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_members', '0008_alter_memberscredentials_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
