# Generated by Django 5.1.4 on 2024-12-26 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_members', '0009_alter_members_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='additionalInfo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='taxId',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='memberscredentials',
            name='credential',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberscredentials',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_credentials', to='modules_members.members'),
        ),
    ]
