# Generated by Django 5.1.4 on 2024-12-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_members', '0010_members_additionalinfo_alter_members_taxid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(blank=True, default='ACTIVE', max_length=150),
        ),
    ]
