# Generated by Django 5.1.4 on 2025-01-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('bankName', models.CharField(max_length=255)),
                ('branchCode', models.CharField(blank=True, max_length=255)),
                ('accountNumber', models.CharField(blank=True, max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ACTIVE', max_length=100)),
            ],
        ),
    ]
