# Generated by Django 5.1.4 on 2024-12-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('entityType', models.CharField(max_length=10)),
                ('taxId', models.CharField(max_length=14, unique=True)),
                ('taxPayer', models.CharField(max_length=150, unique=True)),
                ('companyTaxCategory', models.CharField(blank=True, max_length=50)),
                ('stateRegistration', models.CharField(blank=True, max_length=14)),
                ('cityRegistration', models.CharField(blank=True, max_length=14)),
                ('contactType', models.CharField(max_length=10)),
                ('postCode', models.CharField(blank=True, max_length=8)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('streetAddress', models.CharField(blank=True, max_length=150)),
                ('addressNumber', models.CharField(blank=True, max_length=10)),
                ('neighborhood', models.CharField(blank=True, max_length=50)),
                ('additionalInfo', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('maritalStatus', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
