# Generated by Django 5.1.4 on 2025-01-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_rename_additional_info_business_address_extra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('postcode', models.CharField(blank=True, max_length=8)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('street_address', models.CharField(blank=True, max_length=150)),
                ('building_number', models.CharField(blank=True, max_length=10)),
                ('neighborhood', models.CharField(blank=True, max_length=50)),
                ('address_extra', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.contact')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unkown', 'Unkown')], max_length=50, null=True)),
                ('name', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=150, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_orders', models.PositiveIntegerField(default=0)),
            ],
            bases=('contacts.contact',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.contact')),
                ('legal_name', models.CharField(max_length=150)),
                ('trade_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('ie', models.CharField(blank=True, max_length=14, null=True)),
                ('im', models.CharField(blank=True, max_length=14, null=True)),
            ],
            bases=('contacts.contact',),
        ),
    ]
