# Generated by Django 5.1.4 on 2024-12-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_contacts', '0002_contacts_created_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
