# Generated by Django 5.1.4 on 2025-01-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_additional_info_business_address_extra_and_more'),
        ('contacts', '0002_alter_contact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business.business'),
        ),
    ]
