# Generated by Django 5.1.4 on 2025-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address_extra',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='street_address',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
