# Generated by Django 5.1.4 on 2024-12-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_contacts', '0003_alter_contacts_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='taxId',
            new_name='entityId',
        ),
    ]
