# Generated by Django 5.1.4 on 2025-01-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_street_address_business_address_and_more'),
        ('contacts', '0004_remove_contact_address_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='business',
        ),
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='business.business'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='business.business'),
        ),
    ]
