# Generated by Django 5.1.4 on 2025-01-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_business_customer_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='legal_name',
            new_name='name',
        ),
    ]
