# Generated by Django 5.1.4 on 2024-12-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_contacts', '0005_alter_contacts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='entityId',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
