# Generated by Django 5.1.4 on 2025-01-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_rename_legal_name_supplier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='legal_name',
        ),
    ]
