# Generated by Django 5.1.4 on 2025-01-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('pig', 'Pig'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('other', 'Other')], max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age in months')),
                ('medicalHistory', models.TextField(blank=True)),
                ('arrivalDate', models.DateField(blank=True, null=True)),
                ('slaughterDate', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6)),
                ('carcassWeight', models.DecimalField(blank=True, decimal_places=2, help_text='Carcass weight in kg', max_digits=6, null=True)),
                ('yieldPercentage', models.DecimalField(blank=True, decimal_places=2, help_text='Carcass yield as a percentage of live weight', max_digits=5, null=True)),
                ('fatPercentage', models.DecimalField(decimal_places=2, help_text='Percentage of fat', max_digits=5)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('healthStatus', models.CharField(blank=True, help_text='General health observations', max_length=255)),
                ('vaccinationStatus', models.TextField(blank=True, help_text='Details about vaccinations')),
                ('origin', models.CharField(blank=True, help_text='Farm or source of origin', max_length=255)),
                ('tagNumber', models.CharField(help_text='Unique animal ID or ear tag number', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
            ],
            options={
                'verbose_name_plural': 'Animals',
            },
        ),
    ]
