# Generated by Django 5.1.4 on 2025-01-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('tagNumber', models.CharField(help_text='Unique animal ID or ear tag number', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('pig', 'Pig'), ('sheep', 'Sheep'), ('goat', 'Goat')], max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age in months', null=True)),
                ('status', models.CharField(choices=[('arrival', 'Arrival'), ('growth', 'Growth'), ('ready', 'Ready'), ('sold', 'Sold'), ('processing', 'Processing'), ('slaughtered', 'Slaughtered')], default='arrival', help_text='Current status of the animal or meat', max_length=50)),
                ('origin', models.CharField(blank=True, help_text='Farm or source of origin', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Animals',
            },
        ),
        migrations.CreateModel(
            name='AnimalFinancial',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('purchaseCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maintenanceCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimatedValue', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated live animal value', max_digits=10, null=True)),
                ('sellingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='modules_animals.animal')),
            ],
            options={
                'verbose_name_plural': 'Animals Financial',
            },
        ),
        migrations.CreateModel(
            name='AnimalGrowth',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('feedType', models.CharField(blank=True, help_text='Type of feed provided (e.g., grass-fed, grain-fed)', max_length=255)),
                ('feedConsumed', models.DecimalField(blank=True, decimal_places=2, help_text='Feed consumed in kg', max_digits=5, null=True)),
                ('feedConversionRate', models.DecimalField(blank=True, decimal_places=2, help_text='Feed consumed per kg of weight gained', max_digits=5, null=True)),
                ('GrowthRate', models.DecimalField(blank=True, decimal_places=2, help_text='Growth rate in kg per day', max_digits=5, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='growth', to='modules_animals.animal')),
            ],
            options={
                'verbose_name_plural': 'Animals Growth',
            },
        ),
        migrations.CreateModel(
            name='AnimalHealth',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('healthStatus', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='modules_animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalLifeCycle',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('arrivalDate', models.DateField()),
                ('processedDate', models.DateField(blank=True, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='life_cycle', to='modules_animals.animal')),
            ],
            options={
                'verbose_name_plural': 'Animals Life Cycle',
            },
        ),
        migrations.CreateModel(
            name='AnimalMeatQuality',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('backFatThickness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meat_quality', to='modules_animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalWeight',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in m', max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6)),
                ('processedWeight', models.DecimalField(decimal_places=2, help_text='Weight at processed date in kg', max_digits=6)),
                ('carcassWeight', models.DecimalField(blank=True, decimal_places=2, help_text='Carcass weight in kg', max_digits=6, null=True)),
                ('dressingPercentage', models.DecimalField(blank=True, decimal_places=2, help_text='Carcass yield as a percentage of processed weight', max_digits=5, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='modules_animals.animal')),
            ],
            options={
                'verbose_name_plural': 'Animals Weight',
            },
        ),
        migrations.DeleteModel(
            name='Animals',
        ),
    ]
