# Generated by Django 5.1.4 on 2025-01-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_animals', '0002_animal_animalfinancial_animalgrowth_animalhealth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalhealth',
            options={'verbose_name_plural': 'Animals Health'},
        ),
        migrations.AlterModelOptions(
            name='animalmeatquality',
            options={'verbose_name_plural': 'Animals Meat Quality'},
        ),
    ]
