name: BackEnd QA

on:
  push:
    branches: [ "backend" ]

jobs:
  quality-assurance:
    name: QA
    runs-on: ubuntu-latest
    env:
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}   
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13.1]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pipenv install --deploy --ignore-pipfile
      working-directory: backend

    - name: Run Tests
      run: |
        python manage.py test modules
      working-directory: backend
