name: Deploy to AWS Lightsail

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH into Lightsail & Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/depoc
            git pull origin main
            cd backend
              
            # Compare local Pipfile.lock with the one in the repo
            git diff --quiet Pipfile.lock || {
              echo "Pipfile.lock has changed, installing dependencies.";
              pipenv install --deploy --ignore-pipfile
              echo "pipenv install completed."
            }

            pipenv run python manage.py migrate
            sudo systemctl restart gunicorn.service
            sudo systemctl restart nginx
